/* eslint-disable */


// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : string,
  'nom' : string,
  'createdAt' : Time,
  'email' : string,
  'adresse' : string,
  'listeNoire' : boolean,
  'telephone' : string,
}
export interface DailyMediaEntry {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'relatedDay' : Time,
  'mediaType' : MediaType,
}
export type DayType = { 'conge' : null } |
  { 'work' : null } |
  { 'astreinte' : null };
export type ExternalBlob = Uint8Array;
export interface Fichier {
  'id' : bigint,
  'nom' : string,
  'url' : string,
  'contenu' : ExternalBlob,
  'description' : string,
  'taille' : bigint,
  'typeMime' : string,
  'proprietaire' : Principal,
  'dateAjout' : Time,
}
export interface InterventionAvecPieces {
  'id' : string,
  'clientAbsent' : boolean,
  'estAstreinte' : boolean,
  'date' : Time,
  'createdAt' : Time,
  'user' : Principal,
  'valide' : boolean,
  'heureApremDebutMin' : bigint,
  'heureApremDebutH' : bigint,
  'heureApremFinH' : bigint,
  'signatureIntervenant' : string,
  'heureMatinFinH' : bigint,
  'description' : string,
  'clientAdresse' : string,
  'heureApremFinMin' : bigint,
  'pieces' : Array<PieceUtilisee>,
  'heureMatinDebutMin' : bigint,
  'signatureClient' : string,
  'nomUtilisateur' : string,
  'clientNom' : string,
  'heureMatinDebutH' : bigint,
  'videos' : Array<ExternalBlob>,
  'heureMatinFinMin' : bigint,
  'photos' : Array<ExternalBlob>,
}
export interface InterventionInput {
  'id' : string,
  'clientAbsent' : boolean,
  'estAstreinte' : boolean,
  'date' : Time,
  'heureApremDebutMin' : bigint,
  'heureApremDebutH' : bigint,
  'heureApremFinH' : bigint,
  'signatureIntervenant' : string,
  'heureMatinFinH' : bigint,
  'description' : string,
  'clientAdresse' : string,
  'heureApremFinMin' : bigint,
  'pieces' : Array<PieceUtilisee>,
  'heureMatinDebutMin' : bigint,
  'signatureClient' : string,
  'clientNom' : string,
  'heureMatinDebutH' : bigint,
  'videos' : Array<ExternalBlob>,
  'heureMatinFinMin' : bigint,
  'photos' : Array<ExternalBlob>,
}
export interface InterventionSlot {
  'endHour' : bigint,
  'endMinute' : bigint,
  'startMinute' : bigint,
  'startHour' : bigint,
}
export interface JournalEntry {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'audioUrl' : string,
  'transcription' : string,
  'notes' : string,
  'dayType' : [] | [DayType],
  'photos' : Array<ExternalBlob>,
}
export type MediaType = { 'audio' : ExternalBlob } |
  { 'photo' : ExternalBlob };
export interface MemoEntry {
  'id' : string,
  'content' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'authorName' : string,
  'videos' : Array<ExternalBlob>,
  'photos' : Array<ExternalBlob>,
}
export interface Mission {
  'id' : string,
  'statut' : string,
  'titre' : string,
  'typeMission' : string,
  'createur' : Principal,
  'datePrevue' : Time,
  'description' : string,
  'nomClient' : string,
  'nomDestinataire' : string,
  'nomCreateur' : string,
  'destinataire' : Principal,
  'dateCreation' : Time,
}
export interface PdfReportData {
  'titre' : string,
  'enteteTableau' : Array<string>,
  'periode' : string,
  'totaux' : {
    'heuresTrajet' : string,
    'heuresTravailNormales' : string,
    'heuresAstreinte' : string,
    'heuresRepas' : string,
  },
  'exportTimestamp' : Time,
  'lignesTableau' : Array<Array<string>>,
}
export interface PieceUtilisee {
  'reference' : string,
  'article' : string,
  'quantite' : bigint,
}
export interface PlanningItem {
  'id' : string,
  'statut' : string,
  'titre' : string,
  'typeMission' : string,
  'createur' : Principal,
  'createdAt' : Time,
  'description' : string,
  'nomDestinataire' : string,
  'nomCreateur' : string,
  'destinataire' : Principal,
  'clientNom' : string,
  'dates' : Array<Time>,
}
export interface TicketEssence {
  'id' : string,
  'userId' : Principal,
  'date' : Time,
  'createdAt' : Time,
  'adBluePrixLitre' : [] | [number],
  'immatriculation' : string,
  'kmTotal' : bigint,
  'nomUtilisateur' : string,
  'montant' : number,
  'prixLitre' : number,
  'adBlueMontant' : [] | [number],
  'typeVehicule' : string,
}
export interface TicketResto {
  'id' : string,
  'userId' : Principal,
  'date' : Time,
  'createdAt' : Time,
  'semaineKey' : string,
  'jourSemaine' : string,
  'nomUtilisateur' : string,
  'montant' : number,
}
export type Time = bigint;
export interface TimeEntry {
  'id' : string,
  'heuresTrajet' : bigint,
  'date' : Time,
  'user' : Principal,
  'description' : string,
  'startMorning' : bigint,
  'endAstreinte' : [] | [bigint],
  'interventionSlots' : Array<InterventionSlot>,
  'startAstreinte' : [] | [bigint],
  'endMorning' : bigint,
  'endAfternoon' : bigint,
  'typeOfDay' : DayType,
  'heuresRepas' : bigint,
  'startAfternoon' : bigint,
}
export interface TimeEntryInput {
  'id' : string,
  'heuresTrajet' : bigint,
  'date' : Time,
  'description' : string,
  'startMorning' : bigint,
  'endAstreinte' : [] | [bigint],
  'interventionSlots' : Array<InterventionSlot>,
  'startAstreinte' : [] | [bigint],
  'endMorning' : bigint,
  'endAfternoon' : bigint,
  'typeOfDay' : DayType,
  'heuresRepas' : bigint,
  'startAfternoon' : bigint,
}
export interface Totals {
  'heuresTrajet' : bigint,
  'heuresTravailNormales' : bigint,
  'heuresAstreinte' : bigint,
  'heuresRepas' : bigint,
}
export interface UserProfile {
  'name' : string,
  'signatureIntervenant' : [] | [string],
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehiculeDefaut {
  'lastAdBlueMontant' : [] | [number],
  'immatriculation' : string,
  'typeVehicule' : string,
  'lastAdBluePrixLitre' : [] | [number],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface Contact {
  'id' : string,
  'nom' : string,
  'telephone' : string,
  'email' : string,
  'createdBy' : Principal,
  'createdAt' : Time,
}
export type SectionAccessLevel = { 'full' : null } | { 'readonly' : null } | { 'disabled' : null };
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'accepterMission' : ActorMethod<[string], undefined>,
  'accepterEtCreerEbauche' : ActorMethod<[string, string, string], undefined>,
  'accepterPlanningItem' : ActorMethod<[string], undefined>,
  'setPlanningClientAdresse' : ActorMethod<[string, string], undefined>,
  'ajouterClient' : ActorMethod<[Client], undefined>,
  'ajouterIntervention' : ActorMethod<[InterventionInput], undefined>,
  'ajouterInterventionPourUtilisateur' : ActorMethod<[Principal, InterventionInput], undefined>,
  'ajouterTicketEssence' : ActorMethod<[TicketEssence], undefined>,
  'ajouterTicketResto' : ActorMethod<[TicketResto], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'basculerListeNoire' : ActorMethod<[string], undefined>,
  'calculerNombreAstreinte' : ActorMethod<[Principal], bigint>,
  'calculerNombreConge' : ActorMethod<[Principal], bigint>,
  'calculerTotaux' : ActorMethod<[], Totals>,
  'calculerTotauxPourMois' : ActorMethod<[Principal, bigint, bigint], Totals>,
  'calculerTotauxPourSemaine' : ActorMethod<
    [Principal, bigint, bigint],
    Totals
  >,
  'calculerTotauxPourUtilisateur' : ActorMethod<[Principal], Totals>,
  'compterMissionsEnAttentePourMoi' : ActorMethod<[], bigint>,
  'creerMemo' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, Array<ExternalBlob>],
    undefined
  >,
  'creerMission' : ActorMethod<
    [string, string, Time, Principal, string, string, string, string, string],
    undefined
  >,
  'creerPlanningItem' : ActorMethod<
    [
      string,
      string,
      Array<Time>,
      Principal,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'enregistrerJournal' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>, [] | [DayType]],
    undefined
  >,
  'ajouterContact' : ActorMethod<[string, string, string, string, string], Contact>,
  'obtenirContacts' : ActorMethod<[], Array<Contact>>,
  'supprimerContact' : ActorMethod<[string], boolean>,
  'enregistrerJournee' : ActorMethod<[TimeEntryInput], undefined>,
  'enregistrerMediaQuotidien' : ActorMethod<
    [string, MediaType, Time],
    undefined
  >,
  'estInterventionValidee' : ActorMethod<[string], boolean>,
  'genererDonneesRapportPdf' : ActorMethod<
    [
      { 'semaine' : [bigint, bigint] } |
        { 'mois' : [bigint, bigint] },
      Principal,
    ],
    PdfReportData
  >,
  'getAllCreatedMissionsForCreators' : ActorMethod<[], Array<Mission>>,
  'getAllPendingMissionsForEveryone' : ActorMethod<[], Array<Mission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listerFichiers' : ActorMethod<[], Array<Fichier>>,
  'modifierClient' : ActorMethod<[string, Client], undefined>,
  'modifierDatesPlanningItem' : ActorMethod<[string, Array<Time>], undefined>,
  'modifierIntervention' : ActorMethod<[string, InterventionInput], undefined>,
  'modifierJournal' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>, [] | [DayType]],
    undefined
  >,
  'modifierJournee' : ActorMethod<[string, TimeEntryInput], undefined>,
  'obtenirClients' : ActorMethod<[], Array<Client>>,
  'obtenirInterventionsPourJour' : ActorMethod<
    [Time],
    Array<InterventionAvecPieces>
  >,
  'obtenirInterventionsPubliques' : ActorMethod<
    [Principal],
    Array<InterventionAvecPieces>
  >,
  'obtenirJournaux' : ActorMethod<[], Array<JournalEntry>>,
  'obtenirJournees' : ActorMethod<[], Array<TimeEntry>>,
  'obtenirJourneesPubliques' : ActorMethod<[Principal], Array<TimeEntry>>,
  'obtenirMediasAudioPourJour' : ActorMethod<[Time], Array<ExternalBlob>>,
  'obtenirMediasPourJour' : ActorMethod<[Time], Array<DailyMediaEntry>>,
  'obtenirMemos' : ActorMethod<[], Array<MemoEntry>>,
  'obtenirMissionsCreees' : ActorMethod<[], Array<Mission>>,
  'obtenirMissionsRecues' : ActorMethod<[], Array<Mission>>,
  'obtenirPhotosPourJour' : ActorMethod<[Time], Array<ExternalBlob>>,
  'obtenirPlanningItemsPourJour' : ActorMethod<[Time], Array<PlanningItem>>,
  'obtenirSignatureIntervenant' : ActorMethod<[], [] | [string]>,
  'obtenirTicketsEssence' : ActorMethod<[], Array<TicketEssence>>,
  'obtenirTicketsResto' : ActorMethod<[], Array<TicketResto>>,
  'obtenirTousLesProfils' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'supprimerProfil' : ActorMethod<[Principal], undefined>,
  'obtenirTousPlanningItems' : ActorMethod<[], Array<PlanningItem>>,
  'obtenirToutesInterventions' : ActorMethod<[], Array<InterventionAvecPieces>>,
  'obtenirToutesInterventionsPourFacturation' : ActorMethod<
    [],
    Array<InterventionAvecPieces>
  >,
  'obtenirToutesInterventionsValideesClient' : ActorMethod<[], Array<InterventionAvecPieces>>,
  'obtenirToutesMissionsAcceptees' : ActorMethod<[], Array<Mission>>,
  'obtenirVehiculeDefaut' : ActorMethod<[], [] | [VehiculeDefaut]>,
  'rechercherFichiers' : ActorMethod<[string], Array<Fichier>>,
  'recupererFichier' : ActorMethod<[bigint], [] | [Fichier]>,
  'redigerMissionVersAutre' : ActorMethod<
    [string, Principal, string],
    undefined
  >,
  'restartPublish' : ActorMethod<[], undefined>,
  'sauvegarderSignatureIntervenant' : ActorMethod<[string], undefined>,
  'sauverVehiculeDefaut' : ActorMethod<[VehiculeDefaut], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'definirAccesSection' : ActorMethod<[Principal, string, SectionAccessLevel], undefined>,
  'obtenirAccesSection' : ActorMethod<[Principal, string], SectionAccessLevel>,
  'obtenirTousLesAcces' : ActorMethod<[], Array<[string, SectionAccessLevel]>>,
  'obtenirAccesSectionPourUtilisateur' : ActorMethod<[Principal], Array<[string, SectionAccessLevel]>>,
  'definirStatutCompte' : ActorMethod<[Principal, string], undefined>,
  'obtenirStatutCompte' : ActorMethod<[Principal], string>,
  'obtenirTousStatutsComptes' : ActorMethod<[], Array<[string, string]>>,
  'supprimerClient' : ActorMethod<[string], undefined>,
  'supprimerDeFacturation' : ActorMethod<[string], undefined>,
  'supprimerFichier' : ActorMethod<[bigint], boolean>,
  'supprimerIntervention' : ActorMethod<[string], undefined>,
  'supprimerInterventionDuDossierClient' : ActorMethod<[string], undefined>,
  'supprimerJournal' : ActorMethod<[string], undefined>,
  'supprimerJournee' : ActorMethod<[string], undefined>,
  'supprimerMediaQuotidien' : ActorMethod<[string], undefined>,
  'supprimerMemo' : ActorMethod<[string], undefined>,
  'supprimerMission' : ActorMethod<[string], undefined>,
  'supprimerPlanningItem' : ActorMethod<[string], undefined>,
  'validerPlanningItem' : ActorMethod<[string], undefined>,
  'supprimerTicketEssence' : ActorMethod<[string], boolean>,
  'supprimerTicketResto' : ActorMethod<[string], boolean>,
  'uploadPhotoDansStoic' : ActorMethod<
    [string, ExternalBlob, string, bigint, string],
    [] | [bigint]
  >,
  'validerIntervention' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];