/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : string,
  'nom' : string,
  'createdAt' : Time,
  'email' : string,
  'adresse' : string,
  'listeNoire' : boolean,
  'telephone' : string,
}
export interface DailyMediaEntry {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'relatedDay' : Time,
  'mediaType' : MediaType,
}
export type DayType = { 'conge' : null } |
  { 'work' : null } |
  { 'astreinte' : null };
export type ExternalBlob = Uint8Array;
export interface Fichier {
  'id' : bigint,
  'nom' : string,
  'url' : string,
  'contenu' : ExternalBlob,
  'description' : string,
  'taille' : bigint,
  'typeMime' : string,
  'proprietaire' : Principal,
  'dateAjout' : Time,
}
export interface InterventionAvecPieces {
  'id' : string,
  'date' : Time,
  'createdAt' : Time,
  'user' : Principal,
  'heureApremDebutMin' : bigint,
  'heureApremDebutH' : bigint,
  'heureApremFinH' : bigint,
  'signatureIntervenant' : string,
  'heureMatinFinH' : bigint,
  'description' : string,
  'clientAdresse' : string,
  'heureApremFinMin' : bigint,
  'pieces' : Array<PieceUtilisee>,
  'heureMatinDebutMin' : bigint,
  'signatureClient' : string,
  'clientNom' : string,
  'heureMatinDebutH' : bigint,
  'heureMatinFinMin' : bigint,
}
export interface InterventionInput {
  'id' : string,
  'date' : Time,
  'heureApremDebutMin' : bigint,
  'heureApremDebutH' : bigint,
  'heureApremFinH' : bigint,
  'signatureIntervenant' : string,
  'heureMatinFinH' : bigint,
  'description' : string,
  'clientAdresse' : string,
  'heureApremFinMin' : bigint,
  'pieces' : Array<PieceUtilisee>,
  'heureMatinDebutMin' : bigint,
  'signatureClient' : string,
  'clientNom' : string,
  'heureMatinDebutH' : bigint,
  'heureMatinFinMin' : bigint,
}
export interface InterventionSlot {
  'endHour' : bigint,
  'endMinute' : bigint,
  'startMinute' : bigint,
  'startHour' : bigint,
}
export interface JournalEntry {
  'id' : string,
  'createdAt' : Time,
  'user' : Principal,
  'audioUrl' : string,
  'transcription' : string,
  'notes' : string,
  'dayType' : [] | [DayType],
  'photos' : Array<ExternalBlob>,
}
export type MediaType = { 'audio' : ExternalBlob } |
  { 'photo' : ExternalBlob };
export interface PdfReportData {
  'titre' : string,
  'enteteTableau' : Array<string>,
  'periode' : string,
  'totaux' : {
    'heuresTrajet' : string,
    'heuresTravailNormales' : string,
    'heuresAstreinte' : string,
    'heuresRepas' : string,
  },
  'exportTimestamp' : Time,
  'lignesTableau' : Array<Array<string>>,
}
export interface PieceUtilisee {
  'reference' : string,
  'article' : string,
  'quantite' : bigint,
}
export type Time = bigint;
export interface TimeEntry {
  'id' : string,
  'heuresTrajet' : bigint,
  'date' : Time,
  'user' : Principal,
  'description' : string,
  'startMorning' : bigint,
  'endAstreinte' : [] | [bigint],
  'interventionSlots' : Array<InterventionSlot>,
  'startAstreinte' : [] | [bigint],
  'endMorning' : bigint,
  'endAfternoon' : bigint,
  'typeOfDay' : DayType,
  'heuresRepas' : bigint,
  'startAfternoon' : bigint,
}
export interface TimeEntryInput {
  'id' : string,
  'heuresTrajet' : bigint,
  'date' : Time,
  'description' : string,
  'startMorning' : bigint,
  'endAstreinte' : [] | [bigint],
  'interventionSlots' : Array<InterventionSlot>,
  'startAstreinte' : [] | [bigint],
  'endMorning' : bigint,
  'endAfternoon' : bigint,
  'typeOfDay' : DayType,
  'heuresRepas' : bigint,
  'startAfternoon' : bigint,
}
export interface Totals {
  'heuresTrajet' : bigint,
  'heuresTravailNormales' : bigint,
  'heuresAstreinte' : bigint,
  'heuresRepas' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export declare const MemoEntry: IDL.RecordClass;
export type MemoEntry = {
  id: string;
  authorName: string;
  content: string;
  photos: ExternalBlob[];
  videos: ExternalBlob[];
  createdAt: bigint;
  createdBy: Principal;
};
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'ajouterClient' : ActorMethod<[Client], undefined>,
  'ajouterIntervention' : ActorMethod<[InterventionInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'basculerListeNoire' : ActorMethod<[string], undefined>,
  'calculerNombreAstreinte' : ActorMethod<[Principal], bigint>,
  'calculerNombreConge' : ActorMethod<[Principal], bigint>,
  'calculerTotaux' : ActorMethod<[], Totals>,
  'calculerTotauxPourMois' : ActorMethod<[Principal, bigint, bigint], Totals>,
  'calculerTotauxPourSemaine' : ActorMethod<
    [Principal, bigint, bigint],
    Totals
  >,
  'calculerTotauxPourUtilisateur' : ActorMethod<[Principal], Totals>,
  'enregistrerJournal' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>, [] | [DayType]],
    undefined
  >,
  'enregistrerJournee' : ActorMethod<[TimeEntryInput], undefined>,
  'enregistrerMediaQuotidien' : ActorMethod<
    [string, MediaType, Time],
    undefined
  >,
  'genererDonneesRapportPdf' : ActorMethod<
    [
      { 'semaine' : [bigint, bigint] } |
        { 'mois' : [bigint, bigint] },
      Principal,
    ],
    PdfReportData
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listerFichiers' : ActorMethod<[], Array<Fichier>>,
  'modifierClient' : ActorMethod<[string, Client], undefined>,
  'modifierIntervention' : ActorMethod<[string, InterventionInput], undefined>,
  'modifierJournal' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>, [] | [DayType]],
    undefined
  >,
  'modifierJournee' : ActorMethod<[string, TimeEntryInput], undefined>,
  'obtenirClients' : ActorMethod<[], Array<Client>>,
  'obtenirInterventionsPourJour' : ActorMethod<
    [Time],
    Array<InterventionAvecPieces>
  >,
  'obtenirJournaux' : ActorMethod<[], Array<JournalEntry>>,
  'obtenirJournees' : ActorMethod<[], Array<TimeEntry>>,
  'obtenirMediasAudioPourJour' : ActorMethod<[Time], Array<ExternalBlob>>,
  'obtenirMediasPourJour' : ActorMethod<[Time], Array<DailyMediaEntry>>,
  'obtenirPhotosPourJour' : ActorMethod<[Time], Array<ExternalBlob>>,
  'rechercherFichiers' : ActorMethod<[string], Array<Fichier>>,
  'recupererFichier' : ActorMethod<[bigint], [] | [Fichier]>,
  'restartPublish' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'supprimerClient' : ActorMethod<[string], undefined>,
  'supprimerFichier' : ActorMethod<[bigint], boolean>,
  'supprimerIntervention' : ActorMethod<[string], undefined>,
  'supprimerJournal' : ActorMethod<[string], undefined>,
  'supprimerJournee' : ActorMethod<[string], undefined>,
  'supprimerMediaQuotidien' : ActorMethod<[string], undefined>,
  creerMemo: ActorMethod<[string, string, string, ExternalBlob[], ExternalBlob[]], undefined>;
  obtenirMemos: ActorMethod<[], MemoEntry[]>;
  supprimerMemo: ActorMethod<[string], undefined>;
  obtenirTousLesProfils: ActorMethod<[], Array<[Principal, UserProfile]>>;
  obtenirJourneesPubliques: ActorMethod<[Principal], TimeEntry[]>;
  obtenirInterventionsPubliques: ActorMethod<[Principal], InterventionAvecPieces[]>;
  'uploadPhotoDansStoic' : ActorMethod<
    [string, ExternalBlob, string, bigint, string],
    [] | [bigint]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];