/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Totals = IDL.Record({
  'heuresTrajet' : IDL.Int,
  'heuresTravailNormales' : IDL.Int,
  'heuresAstreinte' : IDL.Int,
  'heuresRepas' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DayType = IDL.Variant({
  'conge' : IDL.Null,
  'work' : IDL.Null,
  'astreinte' : IDL.Null,
});
export const Time = IDL.Int;
export const InterventionSlot = IDL.Record({
  'endHour' : IDL.Int,
  'endMinute' : IDL.Int,
  'startMinute' : IDL.Int,
  'startHour' : IDL.Int,
});
export const TimeEntryInput = IDL.Record({
  'id' : IDL.Text,
  'heuresTrajet' : IDL.Int,
  'date' : Time,
  'description' : IDL.Text,
  'startMorning' : IDL.Int,
  'endAstreinte' : IDL.Opt(IDL.Int),
  'interventionSlots' : IDL.Vec(InterventionSlot),
  'startAstreinte' : IDL.Opt(IDL.Int),
  'endMorning' : IDL.Int,
  'endAfternoon' : IDL.Int,
  'typeOfDay' : DayType,
  'heuresRepas' : IDL.Int,
  'startAfternoon' : IDL.Int,
});
export const MediaType = IDL.Variant({
  'audio' : ExternalBlob,
  'photo' : ExternalBlob,
});
export const PdfReportData = IDL.Record({
  'titre' : IDL.Text,
  'enteteTableau' : IDL.Vec(IDL.Text),
  'periode' : IDL.Text,
  'totaux' : IDL.Record({
    'heuresTrajet' : IDL.Text,
    'heuresTravailNormales' : IDL.Text,
    'heuresAstreinte' : IDL.Text,
    'heuresRepas' : IDL.Text,
  }),
  'exportTimestamp' : Time,
  'lignesTableau' : IDL.Vec(IDL.Vec(IDL.Text)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Fichier = IDL.Record({
  'id' : IDL.Nat,
  'nom' : IDL.Text,
  'url' : IDL.Text,
  'contenu' : ExternalBlob,
  'description' : IDL.Text,
  'taille' : IDL.Nat,
  'typeMime' : IDL.Text,
  'proprietaire' : IDL.Principal,
  'dateAjout' : Time,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'audioUrl' : IDL.Text,
  'transcription' : IDL.Text,
  'notes' : IDL.Text,
  'dayType' : IDL.Opt(DayType),
  'photos' : IDL.Vec(ExternalBlob),
});
export const TimeEntry = IDL.Record({
  'id' : IDL.Text,
  'heuresTrajet' : IDL.Int,
  'date' : Time,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'startMorning' : IDL.Int,
  'endAstreinte' : IDL.Opt(IDL.Int),
  'interventionSlots' : IDL.Vec(InterventionSlot),
  'startAstreinte' : IDL.Opt(IDL.Int),
  'endMorning' : IDL.Int,
  'endAfternoon' : IDL.Int,
  'typeOfDay' : DayType,
  'heuresRepas' : IDL.Int,
  'startAfternoon' : IDL.Int,
});
export const DailyMediaEntry = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'relatedDay' : Time,
  'mediaType' : MediaType,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculerNombreAstreinte' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
  'calculerNombreConge' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
  'calculerTotaux' : IDL.Func([], [Totals], ['query']),
  'calculerTotauxPourMois' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Int],
      [Totals],
      ['query'],
    ),
  'calculerTotauxPourSemaine' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Int],
      [Totals],
      ['query'],
    ),
  'calculerTotauxPourUtilisateur' : IDL.Func(
      [IDL.Principal],
      [Totals],
      ['query'],
    ),
  'enregistrerJournal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Opt(DayType),
      ],
      [],
      [],
    ),
  'enregistrerJournee' : IDL.Func([TimeEntryInput], [], []),
  'enregistrerMediaQuotidien' : IDL.Func([IDL.Text, MediaType, Time], [], []),
  'genererDonneesRapportPdf' : IDL.Func(
      [
        IDL.Variant({
          'semaine' : IDL.Tuple(IDL.Int, IDL.Int),
          'mois' : IDL.Tuple(IDL.Int, IDL.Int),
        }),
        IDL.Principal,
      ],
      [PdfReportData],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listerFichiers' : IDL.Func([], [IDL.Vec(Fichier)], ['query']),
  'modifierJournal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Opt(DayType),
      ],
      [],
      [],
    ),
  'modifierJournee' : IDL.Func([IDL.Text, TimeEntryInput], [], []),
  'obtenirJournaux' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'obtenirJournees' : IDL.Func([], [IDL.Vec(TimeEntry)], ['query']),
  'obtenirMediasAudioPourJour' : IDL.Func(
      [Time],
      [IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'obtenirMediasPourJour' : IDL.Func(
      [Time],
      [IDL.Vec(DailyMediaEntry)],
      ['query'],
    ),
  'obtenirPhotosPourJour' : IDL.Func(
      [Time],
      [IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'rechercherFichiers' : IDL.Func([IDL.Text], [IDL.Vec(Fichier)], ['query']),
  'recupererFichier' : IDL.Func([IDL.Nat], [IDL.Opt(Fichier)], ['query']),
  'restartPublish' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'supprimerFichier' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'supprimerJournal' : IDL.Func([IDL.Text], [], []),
  'supprimerJournee' : IDL.Func([IDL.Text], [], []),
  'supprimerMediaQuotidien' : IDL.Func([IDL.Text], [], []),
  'uploadPhotoDansStoic' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Totals = IDL.Record({
    'heuresTrajet' : IDL.Int,
    'heuresTravailNormales' : IDL.Int,
    'heuresAstreinte' : IDL.Int,
    'heuresRepas' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DayType = IDL.Variant({
    'conge' : IDL.Null,
    'work' : IDL.Null,
    'astreinte' : IDL.Null,
  });
  const Time = IDL.Int;
  const InterventionSlot = IDL.Record({
    'endHour' : IDL.Int,
    'endMinute' : IDL.Int,
    'startMinute' : IDL.Int,
    'startHour' : IDL.Int,
  });
  const TimeEntryInput = IDL.Record({
    'id' : IDL.Text,
    'heuresTrajet' : IDL.Int,
    'date' : Time,
    'description' : IDL.Text,
    'startMorning' : IDL.Int,
    'endAstreinte' : IDL.Opt(IDL.Int),
    'interventionSlots' : IDL.Vec(InterventionSlot),
    'startAstreinte' : IDL.Opt(IDL.Int),
    'endMorning' : IDL.Int,
    'endAfternoon' : IDL.Int,
    'typeOfDay' : DayType,
    'heuresRepas' : IDL.Int,
    'startAfternoon' : IDL.Int,
  });
  const MediaType = IDL.Variant({
    'audio' : ExternalBlob,
    'photo' : ExternalBlob,
  });
  const PdfReportData = IDL.Record({
    'titre' : IDL.Text,
    'enteteTableau' : IDL.Vec(IDL.Text),
    'periode' : IDL.Text,
    'totaux' : IDL.Record({
      'heuresTrajet' : IDL.Text,
      'heuresTravailNormales' : IDL.Text,
      'heuresAstreinte' : IDL.Text,
      'heuresRepas' : IDL.Text,
    }),
    'exportTimestamp' : Time,
    'lignesTableau' : IDL.Vec(IDL.Vec(IDL.Text)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Fichier = IDL.Record({
    'id' : IDL.Nat,
    'nom' : IDL.Text,
    'url' : IDL.Text,
    'contenu' : ExternalBlob,
    'description' : IDL.Text,
    'taille' : IDL.Nat,
    'typeMime' : IDL.Text,
    'proprietaire' : IDL.Principal,
    'dateAjout' : Time,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'audioUrl' : IDL.Text,
    'transcription' : IDL.Text,
    'notes' : IDL.Text,
    'dayType' : IDL.Opt(DayType),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const TimeEntry = IDL.Record({
    'id' : IDL.Text,
    'heuresTrajet' : IDL.Int,
    'date' : Time,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'startMorning' : IDL.Int,
    'endAstreinte' : IDL.Opt(IDL.Int),
    'interventionSlots' : IDL.Vec(InterventionSlot),
    'startAstreinte' : IDL.Opt(IDL.Int),
    'endMorning' : IDL.Int,
    'endAfternoon' : IDL.Int,
    'typeOfDay' : DayType,
    'heuresRepas' : IDL.Int,
    'startAfternoon' : IDL.Int,
  });
  const DailyMediaEntry = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'relatedDay' : Time,
    'mediaType' : MediaType,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculerNombreAstreinte' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
    'calculerNombreConge' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
    'calculerTotaux' : IDL.Func([], [Totals], ['query']),
    'calculerTotauxPourMois' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Int],
        [Totals],
        ['query'],
      ),
    'calculerTotauxPourSemaine' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Int],
        [Totals],
        ['query'],
      ),
    'calculerTotauxPourUtilisateur' : IDL.Func(
        [IDL.Principal],
        [Totals],
        ['query'],
      ),
    'enregistrerJournal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Opt(DayType),
        ],
        [],
        [],
      ),
    'enregistrerJournee' : IDL.Func([TimeEntryInput], [], []),
    'enregistrerMediaQuotidien' : IDL.Func([IDL.Text, MediaType, Time], [], []),
    'genererDonneesRapportPdf' : IDL.Func(
        [
          IDL.Variant({
            'semaine' : IDL.Tuple(IDL.Int, IDL.Int),
            'mois' : IDL.Tuple(IDL.Int, IDL.Int),
          }),
          IDL.Principal,
        ],
        [PdfReportData],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listerFichiers' : IDL.Func([], [IDL.Vec(Fichier)], ['query']),
    'modifierJournal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Opt(DayType),
        ],
        [],
        [],
      ),
    'modifierJournee' : IDL.Func([IDL.Text, TimeEntryInput], [], []),
    'obtenirJournaux' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'obtenirJournees' : IDL.Func([], [IDL.Vec(TimeEntry)], ['query']),
    'obtenirMediasAudioPourJour' : IDL.Func(
        [Time],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'obtenirMediasPourJour' : IDL.Func(
        [Time],
        [IDL.Vec(DailyMediaEntry)],
        ['query'],
      ),
    'obtenirPhotosPourJour' : IDL.Func(
        [Time],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'rechercherFichiers' : IDL.Func([IDL.Text], [IDL.Vec(Fichier)], ['query']),
    'recupererFichier' : IDL.Func([IDL.Nat], [IDL.Opt(Fichier)], ['query']),
    'restartPublish' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'supprimerFichier' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'supprimerJournal' : IDL.Func([IDL.Text], [], []),
    'supprimerJournee' : IDL.Func([IDL.Text], [], []),
    'supprimerMediaQuotidien' : IDL.Func([IDL.Text], [], []),
    'uploadPhotoDansStoic' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };