/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DailyMediaEntry {
    id: string;
    createdAt: Time;
    user: Principal;
    relatedDay: Time;
    mediaType: MediaType;
}
export interface JournalEntry {
    id: string;
    createdAt: Time;
    user: Principal;
    audioUrl: string;
    transcription: string;
    notes: string;
    dayType?: DayType;
    photos: Array<ExternalBlob>;
}
export interface Fichier {
    id: bigint;
    nom: string;
    url: string;
    contenu: ExternalBlob;
    description: string;
    taille: bigint;
    typeMime: string;
    proprietaire: Principal;
    dateAjout: Time;
}
export interface TimeEntryInput {
    id: string;
    heuresTrajet: bigint;
    date: Time;
    description: string;
    startMorning: bigint;
    endAstreinte?: bigint;
    startAstreinte?: bigint;
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
}
export interface Totals {
    heuresTrajet: bigint;
    heuresTravailNormales: bigint;
    heuresAstreinte: bigint;
    heuresRepas: bigint;
}
export interface PdfReportData {
    titre: string;
    enteteTableau: Array<string>;
    periode: string;
    totaux: {
        heuresTrajet: string;
        heuresTravailNormales: string;
        heuresAstreinte: string;
        heuresRepas: string;
    };
    exportTimestamp: Time;
    lignesTableau: Array<Array<string>>;
}
export type MediaType = {
    __kind__: "audio";
    audio: ExternalBlob;
} | {
    __kind__: "photo";
    photo: ExternalBlob;
};
export interface UserProfile {
    name: string;
    email: string;
}
export interface TimeEntry {
    id: string;
    heuresTrajet: bigint;
    date: Time;
    user: Principal;
    description: string;
    startMorning: bigint;
    endAstreinte?: bigint;
    startAstreinte?: bigint;
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
}
export enum DayType {
    conge = "conge",
    work = "work",
    astreinte = "astreinte"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculerNombreAstreinte(user: Principal): Promise<bigint>;
    calculerNombreConge(user: Principal): Promise<bigint>;
    calculerTotaux(): Promise<Totals>;
    calculerTotauxPourMois(user: Principal, mois: bigint, annee: bigint): Promise<Totals>;
    calculerTotauxPourSemaine(user: Principal, semaine: bigint, annee: bigint): Promise<Totals>;
    calculerTotauxPourUtilisateur(user: Principal): Promise<Totals>;
    enregistrerJournal(id: string, audioUrl: string, transcription: string, notes: string, photos: Array<ExternalBlob>, dayType: DayType | null): Promise<void>;
    enregistrerJournee(input: TimeEntryInput): Promise<void>;
    enregistrerMediaQuotidien(id: string, mediaType: MediaType, relatedDay: Time): Promise<void>;
    genererDonneesRapportPdf(typePeriode: {
        __kind__: "semaine";
        semaine: [bigint, bigint];
    } | {
        __kind__: "mois";
        mois: [bigint, bigint];
    }, user: Principal): Promise<PdfReportData>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listerFichiers(): Promise<Array<Fichier>>;
    modifierJournal(id: string, audioUrl: string, transcription: string, notes: string, photos: Array<ExternalBlob>, dayType: DayType | null): Promise<void>;
    modifierJournee(id: string, input: TimeEntryInput): Promise<void>;
    obtenirJournaux(): Promise<Array<JournalEntry>>;
    obtenirJournees(): Promise<Array<TimeEntry>>;
    obtenirMediasAudioPourJour(date: Time): Promise<Array<ExternalBlob>>;
    obtenirMediasPourJour(date: Time): Promise<Array<DailyMediaEntry>>;
    obtenirPhotosPourJour(date: Time): Promise<Array<ExternalBlob>>;
    rechercherFichiers(_motCle: string): Promise<Array<Fichier>>;
    recupererFichier(_id: bigint): Promise<Fichier | null>;
    restartPublish(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    supprimerFichier(_id: bigint): Promise<boolean>;
    supprimerJournal(id: string): Promise<void>;
    supprimerJournee(id: string): Promise<void>;
    supprimerMediaQuotidien(id: string): Promise<void>;
    uploadPhotoDansStoic(filename: string, content: ExternalBlob, mimeType: string, taille: bigint, description: string): Promise<bigint | null>;
}
import type { DailyMediaEntry as _DailyMediaEntry, DayType as _DayType, ExternalBlob as _ExternalBlob, Fichier as _Fichier, JournalEntry as _JournalEntry, MediaType as _MediaType, Time as _Time, TimeEntry as _TimeEntry, TimeEntryInput as _TimeEntryInput, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculerNombreAstreinte(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerNombreAstreinte(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerNombreAstreinte(arg0);
            return result;
        }
    }
    async calculerNombreConge(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerNombreConge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerNombreConge(arg0);
            return result;
        }
    }
    async calculerTotaux(): Promise<Totals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerTotaux();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerTotaux();
            return result;
        }
    }
    async calculerTotauxPourMois(arg0: Principal, arg1: bigint, arg2: bigint): Promise<Totals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerTotauxPourMois(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerTotauxPourMois(arg0, arg1, arg2);
            return result;
        }
    }
    async calculerTotauxPourSemaine(arg0: Principal, arg1: bigint, arg2: bigint): Promise<Totals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerTotauxPourSemaine(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerTotauxPourSemaine(arg0, arg1, arg2);
            return result;
        }
    }
    async calculerTotauxPourUtilisateur(arg0: Principal): Promise<Totals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculerTotauxPourUtilisateur(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculerTotauxPourUtilisateur(arg0);
            return result;
        }
    }
    async enregistrerJournal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<ExternalBlob>, arg5: DayType | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enregistrerJournal(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enregistrerJournal(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async enregistrerJournee(arg0: TimeEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enregistrerJournee(to_candid_TimeEntryInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enregistrerJournee(to_candid_TimeEntryInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async enregistrerMediaQuotidien(arg0: string, arg1: MediaType, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enregistrerMediaQuotidien(arg0, await to_candid_MediaType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enregistrerMediaQuotidien(arg0, await to_candid_MediaType_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async genererDonneesRapportPdf(arg0: {
        __kind__: "semaine";
        semaine: [bigint, bigint];
    } | {
        __kind__: "mois";
        mois: [bigint, bigint];
    }, arg1: Principal): Promise<PdfReportData> {
        if (this.processError) {
            try {
                const result = await this.actor.genererDonneesRapportPdf(to_candid_variant_n19(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.genererDonneesRapportPdf(to_candid_variant_n19(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listerFichiers(): Promise<Array<Fichier>> {
        if (this.processError) {
            try {
                const result = await this.actor.listerFichiers();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listerFichiers();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async modifierJournal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<ExternalBlob>, arg5: DayType | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifierJournal(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifierJournal(arg0, arg1, arg2, arg3, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async modifierJournee(arg0: string, arg1: TimeEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifierJournee(arg0, to_candid_TimeEntryInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifierJournee(arg0, to_candid_TimeEntryInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async obtenirJournaux(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirJournaux();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirJournaux();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirJournees(): Promise<Array<TimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirJournees();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirJournees();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirMediasAudioPourJour(arg0: Time): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirMediasAudioPourJour(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirMediasAudioPourJour(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirMediasPourJour(arg0: Time): Promise<Array<DailyMediaEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirMediasPourJour(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirMediasPourJour(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async obtenirPhotosPourJour(arg0: Time): Promise<Array<ExternalBlob>> {
        if (this.processError) {
            try {
                const result = await this.actor.obtenirPhotosPourJour(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.obtenirPhotosPourJour(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async rechercherFichiers(arg0: string): Promise<Array<Fichier>> {
        if (this.processError) {
            try {
                const result = await this.actor.rechercherFichiers(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rechercherFichiers(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async recupererFichier(arg0: bigint): Promise<Fichier | null> {
        if (this.processError) {
            try {
                const result = await this.actor.recupererFichier(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recupererFichier(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async restartPublish(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restartPublish();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restartPublish();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async supprimerFichier(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.supprimerFichier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supprimerFichier(arg0);
            return result;
        }
    }
    async supprimerJournal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supprimerJournal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supprimerJournal(arg0);
            return result;
        }
    }
    async supprimerJournee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supprimerJournee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supprimerJournee(arg0);
            return result;
        }
    }
    async supprimerMediaQuotidien(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supprimerMediaQuotidien(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supprimerMediaQuotidien(arg0);
            return result;
        }
    }
    async uploadPhotoDansStoic(arg0: string, arg1: ExternalBlob, arg2: string, arg3: bigint, arg4: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhotoDansStoic(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhotoDansStoic(arg0, await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_DailyMediaEntry_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyMediaEntry): Promise<DailyMediaEntry> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DayType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayType): DayType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Fichier_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fichier): Promise<Fichier> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_JournalEntry_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): Promise<JournalEntry> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): Promise<MediaType> {
    return await from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TimeEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeEntry): TimeEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DayType]): DayType | null {
    return value.length === 0 ? null : from_candid_DayType_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Fichier]): Promise<Fichier | null> {
    return value.length === 0 ? null : await from_candid_Fichier_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    nom: string;
    url: string;
    contenu: _ExternalBlob;
    description: string;
    taille: bigint;
    typeMime: string;
    proprietaire: Principal;
    dateAjout: _Time;
}): Promise<{
    id: bigint;
    nom: string;
    url: string;
    contenu: ExternalBlob;
    description: string;
    taille: bigint;
    typeMime: string;
    proprietaire: Principal;
    dateAjout: Time;
}> {
    return {
        id: value.id,
        nom: value.nom,
        url: value.url,
        contenu: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.contenu),
        description: value.description,
        taille: value.taille,
        typeMime: value.typeMime,
        proprietaire: value.proprietaire,
        dateAjout: value.dateAjout
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    user: Principal;
    audioUrl: string;
    transcription: string;
    notes: string;
    dayType: [] | [_DayType];
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    createdAt: Time;
    user: Principal;
    audioUrl: string;
    transcription: string;
    notes: string;
    dayType?: DayType;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        user: value.user,
        audioUrl: value.audioUrl,
        transcription: value.transcription,
        notes: value.notes,
        dayType: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.dayType)),
        photos: await from_candid_vec_n33(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    heuresTrajet: bigint;
    date: _Time;
    user: Principal;
    description: string;
    startMorning: bigint;
    endAstreinte: [] | [bigint];
    startAstreinte: [] | [bigint];
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: _DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
}): {
    id: string;
    heuresTrajet: bigint;
    date: Time;
    user: Principal;
    description: string;
    startMorning: bigint;
    endAstreinte?: bigint;
    startAstreinte?: bigint;
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
} {
    return {
        id: value.id,
        heuresTrajet: value.heuresTrajet,
        date: value.date,
        user: value.user,
        description: value.description,
        startMorning: value.startMorning,
        endAstreinte: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.endAstreinte)),
        startAstreinte: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.startAstreinte)),
        endMorning: value.endMorning,
        endAfternoon: value.endAfternoon,
        typeOfDay: from_candid_DayType_n31(_uploadFile, _downloadFile, value.typeOfDay),
        heuresRepas: value.heuresRepas,
        startAfternoon: value.startAfternoon
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: _Time;
    user: Principal;
    relatedDay: _Time;
    mediaType: _MediaType;
}): Promise<{
    id: string;
    createdAt: Time;
    user: Principal;
    relatedDay: Time;
    mediaType: MediaType;
}> {
    return {
        id: value.id,
        createdAt: value.createdAt,
        user: value.user,
        relatedDay: value.relatedDay,
        mediaType: await from_candid_MediaType_n41(_uploadFile, _downloadFile, value.mediaType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    conge: null;
} | {
    work: null;
} | {
    astreinte: null;
}): DayType {
    return "conge" in value ? DayType.conge : "work" in value ? DayType.work : "astreinte" in value ? DayType.astreinte : value;
}
async function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: _ExternalBlob;
} | {
    photo: _ExternalBlob;
}): Promise<{
    __kind__: "audio";
    audio: ExternalBlob;
} | {
    __kind__: "photo";
    photo: ExternalBlob;
}> {
    return "audio" in value ? {
        __kind__: "audio",
        audio: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.audio)
    } : "photo" in value ? {
        __kind__: "photo",
        photo: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.photo)
    } : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Fichier>): Promise<Array<Fichier>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Fichier_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Promise<Array<JournalEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_JournalEntry_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimeEntry>): Array<TimeEntry> {
    return value.map((x)=>from_candid_TimeEntry_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyMediaEntry>): Promise<Array<DailyMediaEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DailyMediaEntry_n39(_uploadFile, _downloadFile, x)));
}
function to_candid_DayType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayType): _DayType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MediaType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): Promise<_MediaType> {
    return await to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TimeEntryInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeEntryInput): _TimeEntryInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayType | null): [] | [_DayType] {
    return value === null ? candid_none() : candid_some(to_candid_DayType_n13(_uploadFile, _downloadFile, value));
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    heuresTrajet: bigint;
    date: Time;
    description: string;
    startMorning: bigint;
    endAstreinte?: bigint;
    startAstreinte?: bigint;
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
}): {
    id: string;
    heuresTrajet: bigint;
    date: _Time;
    description: string;
    startMorning: bigint;
    endAstreinte: [] | [bigint];
    startAstreinte: [] | [bigint];
    endMorning: bigint;
    endAfternoon: bigint;
    typeOfDay: _DayType;
    heuresRepas: bigint;
    startAfternoon: bigint;
} {
    return {
        id: value.id,
        heuresTrajet: value.heuresTrajet,
        date: value.date,
        description: value.description,
        startMorning: value.startMorning,
        endAstreinte: value.endAstreinte ? candid_some(value.endAstreinte) : candid_none(),
        startAstreinte: value.startAstreinte ? candid_some(value.startAstreinte) : candid_none(),
        endMorning: value.endMorning,
        endAfternoon: value.endAfternoon,
        typeOfDay: to_candid_DayType_n13(_uploadFile, _downloadFile, value.typeOfDay),
        heuresRepas: value.heuresRepas,
        startAfternoon: value.startAfternoon
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayType): {
    conge: null;
} | {
    work: null;
} | {
    astreinte: null;
} {
    return value == DayType.conge ? {
        conge: null
    } : value == DayType.work ? {
        work: null
    } : value == DayType.astreinte ? {
        astreinte: null
    } : value;
}
async function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "audio";
    audio: ExternalBlob;
} | {
    __kind__: "photo";
    photo: ExternalBlob;
}): Promise<{
    audio: _ExternalBlob;
} | {
    photo: _ExternalBlob;
}> {
    return value.__kind__ === "audio" ? {
        audio: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.audio)
    } : value.__kind__ === "photo" ? {
        photo: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.photo)
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "semaine";
    semaine: [bigint, bigint];
} | {
    __kind__: "mois";
    mois: [bigint, bigint];
}): {
    semaine: [bigint, bigint];
} | {
    mois: [bigint, bigint];
} {
    return value.__kind__ === "semaine" ? {
        semaine: value.semaine
    } : value.__kind__ === "mois" ? {
        mois: value.mois
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
